#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <math.h>

bool func0(double w, double x, double y, double z) {
  return w * sqrt(x) + y > z;
}

bool func1(double w, double x, double y, double z) {
  return w * sqrt(x) + y < z;
}

bool func2(double w, double x, double y, double z) {
  return w * sqrt(x) + y >= z;
}

bool func3(double w, double x, double y, double z) {
  return w * sqrt(x) + y <= z;
}

bool func4(double a, double b, double c, double d) {
  return a / b + c > d;
}

bool func5(double a, double b, double c, double d) {
  return a / b + c < d;
}

bool func6(double a, double b, double c, double d) {
  return a / b + c >= d;
}

bool func7(double a, double b, double c, double d) {
  return a / b + c <= d;
}

#pragma clang optimize off

typedef struct {
  double a, b, c, d;
  bool b0, b1, b2, b3, b4, b5, b6, b7;
} Case;

#if 1
Case cases[] =
  {
   { -3, -3, -3, -3, false, true , false, true , true , false, true , false},
   { -2, -3, -3, -3, false, true , false, true , true , false, true , false},
   { -1, -3, -3, -3, false, true , false, true , true , false, true , false},
   { +0, -3, -3, -3, false, false, true , true , false, false, true , true },
   { +1, -3, -3, -3, true , false, true , false, false, true , false, true },
   { -3, -2, -3, -3, false, true , false, true , true , false, true , false},
   { -2, -2, -3, -3, false, true , false, true , true , false, true , false},
   { -1, -2, -3, -3, false, true , false, true , true , false, true , false},
   { +0, -2, -3, -3, false, false, true , true , false, false, true , true },
   { +1, -2, -3, -3, true , false, true , false, false, true , false, true },
   { -3, -1, -3, -3, false, true , false, true , true , false, true , false},
   { -2, -1, -3, -3, false, true , false, true , true , false, true , false},
   { -1, -1, -3, -3, false, true , false, true , true , false, true , false},
   { +0, -1, -3, -3, false, false, true , true , false, false, true , true },
   { +1, -1, -3, -3, true , false, true , false, false, true , false, true },
   { -3, +0, -3, -3, false, false, true , true , false, true , false, true },
   { -2, +0, -3, -3, false, false, true , true , false, true , false, true },
   { -1, +0, -3, -3, false, false, true , true , false, true , false, true },
   { +0, +0, -3, -3, false, false, true , true , false, false, false, false},
   { +1, +0, -3, -3, false, false, true , true , true , false, true , false},
   { -3, +1, -3, -3, false, true , false, true , false, true , false, true },
   { -2, +1, -3, -3, false, true , false, true , false, true , false, true },
   { -1, +1, -3, -3, false, true , false, true , false, true , false, true },
   { +0, +1, -3, -3, false, false, true , true , false, false, true , true },
   { +1, +1, -3, -3, true , false, true , false, true , false, true , false},
   { -3, -3, -2, -3, false, true , false, true , true , false, true , false},
   { -2, -3, -2, -3, false, true , false, true , true , false, true , false},
   { -1, -3, -2, -3, false, true , false, true , true , false, true , false},
   { +0, -3, -2, -3, true , false, true , false, true , false, true , false},
   { +1, -3, -2, -3, true , false, true , false, true , false, true , false},
   { -3, -2, -2, -3, false, true , false, true , true , false, true , false},
   { -2, -2, -2, -3, false, true , false, true , true , false, true , false},
   { -1, -2, -2, -3, false, true , false, true , true , false, true , false},
   { +0, -2, -2, -3, true , false, true , false, true , false, true , false},
   { +1, -2, -2, -3, true , false, true , false, true , false, true , false},
   { -3, -1, -2, -3, false, true , false, true , true , false, true , false},
   { -2, -1, -2, -3, false, true , false, true , true , false, true , false},
   { -1, -1, -2, -3, false, false, true , true , true , false, true , false},
   { +0, -1, -2, -3, true , false, true , false, true , false, true , false},
   { +1, -1, -2, -3, true , false, true , false, false, false, true , true },
   { -3, +0, -2, -3, true , false, true , false, false, true , false, true },
   { -2, +0, -2, -3, true , false, true , false, false, true , false, true },
   { -1, +0, -2, -3, true , false, true , false, false, true , false, true },
   { +0, +0, -2, -3, true , false, true , false, false, false, false, false},
   { +1, +0, -2, -3, true , false, true , false, true , false, true , false},
   { -3, +1, -2, -3, false, true , false, true , false, true , false, true },
   { -2, +1, -2, -3, false, true , false, true , false, true , false, true },
   { -1, +1, -2, -3, false, false, true , true , false, false, true , true },
   { +0, +1, -2, -3, true , false, true , false, true , false, true , false},
   { +1, +1, -2, -3, true , false, true , false, true , false, true , false},
   { -3, -3, -1, -3, false, true , false, true , true , false, true , false},
   { -2, -3, -1, -3, false, true , false, true , true , false, true , false},
   { -1, -3, -1, -3, true , false, true , false, true , false, true , false},
   { +0, -3, -1, -3, true , false, true , false, true , false, true , false},
   { +1, -3, -1, -3, true , false, true , false, true , false, true , false},
   { -3, -2, -1, -3, false, true , false, true , true , false, true , false},
   { -2, -2, -1, -3, false, true , false, true , true , false, true , false},
   { -1, -2, -1, -3, true , false, true , false, true , false, true , false},
   { +0, -2, -1, -3, true , false, true , false, true , false, true , false},
   { +1, -2, -1, -3, true , false, true , false, true , false, true , false},
   { -3, -1, -1, -3, false, true , false, true , true , false, true , false},
   { -2, -1, -1, -3, false, false, true , true , true , false, true , false},
   { -1, -1, -1, -3, true , false, true , false, true , false, true , false},
   { +0, -1, -1, -3, true , false, true , false, true , false, true , false},
   { +1, -1, -1, -3, true , false, true , false, true , false, true , false},
   { -3, +0, -1, -3, true , false, true , false, false, true , false, true },
   { -2, +0, -1, -3, true , false, true , false, false, true , false, true },
   { -1, +0, -1, -3, true , false, true , false, false, true , false, true },
   { +0, +0, -1, -3, true , false, true , false, false, false, false, false},
   { +1, +0, -1, -3, true , false, true , false, true , false, true , false},
   { -3, +1, -1, -3, false, true , false, true , false, true , false, true },
   { -2, +1, -1, -3, false, false, true , true , false, false, true , true },
   { -1, +1, -1, -3, true , false, true , false, true , false, true , false},
   { +0, +1, -1, -3, true , false, true , false, true , false, true , false},
   { +1, +1, -1, -3, true , false, true , false, true , false, true , false},
   { -3, -3, +0, -3, false, true , false, true , true , false, true , false},
   { -2, -3, +0, -3, false, true , false, true , true , false, true , false},
   { -1, -3, +0, -3, true , false, true , false, true , false, true , false},
   { +0, -3, +0, -3, true , false, true , false, true , false, true , false},
   { +1, -3, +0, -3, true , false, true , false, true , false, true , false},
   { -3, -2, +0, -3, false, true , false, true , true , false, true , false},
   { -2, -2, +0, -3, true , false, true , false, true , false, true , false},
   { -1, -2, +0, -3, true , false, true , false, true , false, true , false},
   { +0, -2, +0, -3, true , false, true , false, true , false, true , false},
   { +1, -2, +0, -3, true , false, true , false, true , false, true , false},
   { -3, -1, +0, -3, false, false, true , true , true , false, true , false},
   { -2, -1, +0, -3, true , false, true , false, true , false, true , false},
   { -1, -1, +0, -3, true , false, true , false, true , false, true , false},
   { +0, -1, +0, -3, true , false, true , false, true , false, true , false},
   { +1, -1, +0, -3, true , false, true , false, true , false, true , false},
   { -3, +0, +0, -3, true , false, true , false, false, true , false, true },
   { -2, +0, +0, -3, true , false, true , false, false, true , false, true },
   { -1, +0, +0, -3, true , false, true , false, false, true , false, true },
   { +0, +0, +0, -3, true , false, true , false, false, false, false, false},
   { +1, +0, +0, -3, true , false, true , false, true , false, true , false},
   { -3, +1, +0, -3, false, false, true , true , false, false, true , true },
   { -2, +1, +0, -3, true , false, true , false, true , false, true , false},
   { -1, +1, +0, -3, true , false, true , false, true , false, true , false},
   { +0, +1, +0, -3, true , false, true , false, true , false, true , false},
   { +1, +1, +0, -3, true , false, true , false, true , false, true , false},
   { -3, -3, +1, -3, false, true , false, true , true , false, true , false},
   { -2, -3, +1, -3, true , false, true , false, true , false, true , false},
   { -1, -3, +1, -3, true , false, true , false, true , false, true , false},
   { +0, -3, +1, -3, true , false, true , false, true , false, true , false},
   { +1, -3, +1, -3, true , false, true , false, true , false, true , false},
   { -3, -2, +1, -3, false, true , false, true , true , false, true , false},
   { -2, -2, +1, -3, true , false, true , false, true , false, true , false},
   { -1, -2, +1, -3, true , false, true , false, true , false, true , false},
   { +0, -2, +1, -3, true , false, true , false, true , false, true , false},
   { +1, -2, +1, -3, true , false, true , false, true , false, true , false},
   { -3, -1, +1, -3, true , false, true , false, true , false, true , false},
   { -2, -1, +1, -3, true , false, true , false, true , false, true , false},
   { -1, -1, +1, -3, true , false, true , false, true , false, true , false},
   { +0, -1, +1, -3, true , false, true , false, true , false, true , false},
   { +1, -1, +1, -3, true , false, true , false, true , false, true , false},
   { -3, +0, +1, -3, true , false, true , false, false, true , false, true },
   { -2, +0, +1, -3, true , false, true , false, false, true , false, true },
   { -1, +0, +1, -3, true , false, true , false, false, true , false, true },
   { +0, +0, +1, -3, true , false, true , false, false, false, false, false},
   { +1, +0, +1, -3, true , false, true , false, true , false, true , false},
   { -3, +1, +1, -3, true , false, true , false, true , false, true , false},
   { -2, +1, +1, -3, true , false, true , false, true , false, true , false},
   { -1, +1, +1, -3, true , false, true , false, true , false, true , false},
   { +0, +1, +1, -3, true , false, true , false, true , false, true , false},
   { +1, +1, +1, -3, true , false, true , false, true , false, true , false},
   { -3, -3, -3, -2, false, true , false, true , false, false, true , true },
   { -2, -3, -3, -2, false, true , false, true , false, true , false, true },
   { -1, -3, -3, -2, false, true , false, true , false, true , false, true },
   { +0, -3, -3, -2, false, true , false, true , false, true , false, true },
   { +1, -3, -3, -2, true , false, true , false, false, true , false, true },
   { -3, -2, -3, -2, false, true , false, true , true , false, true , false},
   { -2, -2, -3, -2, false, true , false, true , false, false, true , true },
   { -1, -2, -3, -2, false, true , false, true , false, true , false, true },
   { +0, -2, -3, -2, false, true , false, true , false, true , false, true },
   { +1, -2, -3, -2, true , false, true , false, false, true , false, true },
   { -3, -1, -3, -2, false, true , false, true , true , false, true , false},
   { -2, -1, -3, -2, false, true , false, true , true , false, true , false},
   { -1, -1, -3, -2, false, true , false, true , false, false, true , true },
   { +0, -1, -3, -2, false, true , false, true , false, true , false, true },
   { +1, -1, -3, -2, false, false, true , true , false, true , false, true },
   { -3, +0, -3, -2, false, true , false, true , false, true , false, true },
   { -2, +0, -3, -2, false, true , false, true , false, true , false, true },
   { -1, +0, -3, -2, false, true , false, true , false, true , false, true },
   { +0, +0, -3, -2, false, true , false, true , false, false, false, false},
   { +1, +0, -3, -2, false, true , false, true , true , false, true , false},
   { -3, +1, -3, -2, false, true , false, true , false, true , false, true },
   { -2, +1, -3, -2, false, true , false, true , false, true , false, true },
   { -1, +1, -3, -2, false, true , false, true , false, true , false, true },
   { +0, +1, -3, -2, false, true , false, true , false, true , false, true },
   { +1, +1, -3, -2, false, false, true , true , false, false, true , true },
   { -3, -3, -2, -2, false, true , false, true , true , false, true , false},
   { -2, -3, -2, -2, false, true , false, true , true , false, true , false},
   { -1, -3, -2, -2, false, true , false, true , true , false, true , false},
   { +0, -3, -2, -2, false, false, true , true , false, false, true , true },
   { +1, -3, -2, -2, true , false, true , false, false, true , false, true },
   { -3, -2, -2, -2, false, true , false, true , true , false, true , false},
   { -2, -2, -2, -2, false, true , false, true , true , false, true , false},
   { -1, -2, -2, -2, false, true , false, true , true , false, true , false},
   { +0, -2, -2, -2, false, false, true , true , false, false, true , true },
   { +1, -2, -2, -2, true , false, true , false, false, true , false, true },
   { -3, -1, -2, -2, false, true , false, true , true , false, true , false},
   { -2, -1, -2, -2, false, true , false, true , true , false, true , false},
   { -1, -1, -2, -2, false, true , false, true , true , false, true , false},
   { +0, -1, -2, -2, false, false, true , true , false, false, true , true },
   { +1, -1, -2, -2, true , false, true , false, false, true , false, true },
   { -3, +0, -2, -2, false, false, true , true , false, true , false, true },
   { -2, +0, -2, -2, false, false, true , true , false, true , false, true },
   { -1, +0, -2, -2, false, false, true , true , false, true , false, true },
   { +0, +0, -2, -2, false, false, true , true , false, false, false, false},
   { +1, +0, -2, -2, false, false, true , true , true , false, true , false},
   { -3, +1, -2, -2, false, true , false, true , false, true , false, true },
   { -2, +1, -2, -2, false, true , false, true , false, true , false, true },
   { -1, +1, -2, -2, false, true , false, true , false, true , false, true },
   { +0, +1, -2, -2, false, false, true , true , false, false, true , true },
   { +1, +1, -2, -2, true , false, true , false, true , false, true , false},
   { -3, -3, -1, -2, false, true , false, true , true , false, true , false},
   { -2, -3, -1, -2, false, true , false, true , true , false, true , false},
   { -1, -3, -1, -2, false, true , false, true , true , false, true , false},
   { +0, -3, -1, -2, true , false, true , false, true , false, true , false},
   { +1, -3, -1, -2, true , false, true , false, true , false, true , false},
   { -3, -2, -1, -2, false, true , false, true , true , false, true , false},
   { -2, -2, -1, -2, false, true , false, true , true , false, true , false},
   { -1, -2, -1, -2, false, true , false, true , true , false, true , false},
   { +0, -2, -1, -2, true , false, true , false, true , false, true , false},
   { +1, -2, -1, -2, true , false, true , false, true , false, true , false},
   { -3, -1, -1, -2, false, true , false, true , true , false, true , false},
   { -2, -1, -1, -2, false, true , false, true , true , false, true , false},
   { -1, -1, -1, -2, false, false, true , true , true , false, true , false},
   { +0, -1, -1, -2, true , false, true , false, true , false, true , false},
   { +1, -1, -1, -2, true , false, true , false, false, false, true , true },
   { -3, +0, -1, -2, true , false, true , false, false, true , false, true },
   { -2, +0, -1, -2, true , false, true , false, false, true , false, true },
   { -1, +0, -1, -2, true , false, true , false, false, true , false, true },
   { +0, +0, -1, -2, true , false, true , false, false, false, false, false},
   { +1, +0, -1, -2, true , false, true , false, true , false, true , false},
   { -3, +1, -1, -2, false, true , false, true , false, true , false, true },
   { -2, +1, -1, -2, false, true , false, true , false, true , false, true },
   { -1, +1, -1, -2, false, false, true , true , false, false, true , true },
   { +0, +1, -1, -2, true , false, true , false, true , false, true , false},
   { +1, +1, -1, -2, true , false, true , false, true , false, true , false},
   { -3, -3, +0, -2, false, true , false, true , true , false, true , false},
   { -2, -3, +0, -2, false, true , false, true , true , false, true , false},
   { -1, -3, +0, -2, true , false, true , false, true , false, true , false},
   { +0, -3, +0, -2, true , false, true , false, true , false, true , false},
   { +1, -3, +0, -2, true , false, true , false, true , false, true , false},
   { -3, -2, +0, -2, false, true , false, true , true , false, true , false},
   { -2, -2, +0, -2, false, true , false, true , true , false, true , false},
   { -1, -2, +0, -2, true , false, true , false, true , false, true , false},
   { +0, -2, +0, -2, true , false, true , false, true , false, true , false},
   { +1, -2, +0, -2, true , false, true , false, true , false, true , false},
   { -3, -1, +0, -2, false, true , false, true , true , false, true , false},
   { -2, -1, +0, -2, false, false, true , true , true , false, true , false},
   { -1, -1, +0, -2, true , false, true , false, true , false, true , false},
   { +0, -1, +0, -2, true , false, true , false, true , false, true , false},
   { +1, -1, +0, -2, true , false, true , false, true , false, true , false},
   { -3, +0, +0, -2, true , false, true , false, false, true , false, true },
   { -2, +0, +0, -2, true , false, true , false, false, true , false, true },
   { -1, +0, +0, -2, true , false, true , false, false, true , false, true },
   { +0, +0, +0, -2, true , false, true , false, false, false, false, false},
   { +1, +0, +0, -2, true , false, true , false, true , false, true , false},
   { -3, +1, +0, -2, false, true , false, true , false, true , false, true },
   { -2, +1, +0, -2, false, false, true , true , false, false, true , true },
   { -1, +1, +0, -2, true , false, true , false, true , false, true , false},
   { +0, +1, +0, -2, true , false, true , false, true , false, true , false},
   { +1, +1, +0, -2, true , false, true , false, true , false, true , false},
   { -3, -3, +1, -2, false, true , false, true , true , false, true , false},
   { -2, -3, +1, -2, false, true , false, true , true , false, true , false},
   { -1, -3, +1, -2, true , false, true , false, true , false, true , false},
   { +0, -3, +1, -2, true , false, true , false, true , false, true , false},
   { +1, -3, +1, -2, true , false, true , false, true , false, true , false},
   { -3, -2, +1, -2, false, true , false, true , true , false, true , false},
   { -2, -2, +1, -2, true , false, true , false, true , false, true , false},
   { -1, -2, +1, -2, true , false, true , false, true , false, true , false},
   { +0, -2, +1, -2, true , false, true , false, true , false, true , false},
   { +1, -2, +1, -2, true , false, true , false, true , false, true , false},
   { -3, -1, +1, -2, false, false, true , true , true , false, true , false},
   { -2, -1, +1, -2, true , false, true , false, true , false, true , false},
   { -1, -1, +1, -2, true , false, true , false, true , false, true , false},
   { +0, -1, +1, -2, true , false, true , false, true , false, true , false},
   { +1, -1, +1, -2, true , false, true , false, true , false, true , false},
   { -3, +0, +1, -2, true , false, true , false, false, true , false, true },
   { -2, +0, +1, -2, true , false, true , false, false, true , false, true },
   { -1, +0, +1, -2, true , false, true , false, false, true , false, true },
   { +0, +0, +1, -2, true , false, true , false, false, false, false, false},
   { +1, +0, +1, -2, true , false, true , false, true , false, true , false},
   { -3, +1, +1, -2, false, false, true , true , false, false, true , true },
   { -2, +1, +1, -2, true , false, true , false, true , false, true , false},
   { -1, +1, +1, -2, true , false, true , false, true , false, true , false},
   { +0, +1, +1, -2, true , false, true , false, true , false, true , false},
   { +1, +1, +1, -2, true , false, true , false, true , false, true , false},
   { -3, -3, -3, -1, false, true , false, true , false, true , false, true },
   { -2, -3, -3, -1, false, true , false, true , false, true , false, true },
   { -1, -3, -3, -1, false, true , false, true , false, true , false, true },
   { +0, -3, -3, -1, false, true , false, true , false, true , false, true },
   { +1, -3, -3, -1, false, true , false, true , false, true , false, true },
   { -3, -2, -3, -1, false, true , false, true , false, true , false, true },
   { -2, -2, -3, -1, false, true , false, true , false, true , false, true },
   { -1, -2, -3, -1, false, true , false, true , false, true , false, true },
   { +0, -2, -3, -1, false, true , false, true , false, true , false, true },
   { +1, -2, -3, -1, false, true , false, true , false, true , false, true },
   { -3, -1, -3, -1, false, true , false, true , true , false, true , false},
   { -2, -1, -3, -1, false, true , false, true , false, false, true , true },
   { -1, -1, -3, -1, false, true , false, true , false, true , false, true },
   { +0, -1, -3, -1, false, true , false, true , false, true , false, true },
   { +1, -1, -3, -1, false, true , false, true , false, true , false, true },
   { -3, +0, -3, -1, false, true , false, true , false, true , false, true },
   { -2, +0, -3, -1, false, true , false, true , false, true , false, true },
   { -1, +0, -3, -1, false, true , false, true , false, true , false, true },
   { +0, +0, -3, -1, false, true , false, true , false, false, false, false},
   { +1, +0, -3, -1, false, true , false, true , true , false, true , false},
   { -3, +1, -3, -1, false, true , false, true , false, true , false, true },
   { -2, +1, -3, -1, false, true , false, true , false, true , false, true },
   { -1, +1, -3, -1, false, true , false, true , false, true , false, true },
   { +0, +1, -3, -1, false, true , false, true , false, true , false, true },
   { +1, +1, -3, -1, false, true , false, true , false, true , false, true },
   { -3, -3, -2, -1, false, true , false, true , false, false, true , true },
   { -2, -3, -2, -1, false, true , false, true , false, true , false, true },
   { -1, -3, -2, -1, false, true , false, true , false, true , false, true },
   { +0, -3, -2, -1, false, true , false, true , false, true , false, true },
   { +1, -3, -2, -1, true , false, true , false, false, true , false, true },
   { -3, -2, -2, -1, false, true , false, true , true , false, true , false},
   { -2, -2, -2, -1, false, true , false, true , false, false, true , true },
   { -1, -2, -2, -1, false, true , false, true , false, true , false, true },
   { +0, -2, -2, -1, false, true , false, true , false, true , false, true },
   { +1, -2, -2, -1, true , false, true , false, false, true , false, true },
   { -3, -1, -2, -1, false, true , false, true , true , false, true , false},
   { -2, -1, -2, -1, false, true , false, true , true , false, true , false},
   { -1, -1, -2, -1, false, true , false, true , false, false, true , true },
   { +0, -1, -2, -1, false, true , false, true , false, true , false, true },
   { +1, -1, -2, -1, false, false, true , true , false, true , false, true },
   { -3, +0, -2, -1, false, true , false, true , false, true , false, true },
   { -2, +0, -2, -1, false, true , false, true , false, true , false, true },
   { -1, +0, -2, -1, false, true , false, true , false, true , false, true },
   { +0, +0, -2, -1, false, true , false, true , false, false, false, false},
   { +1, +0, -2, -1, false, true , false, true , true , false, true , false},
   { -3, +1, -2, -1, false, true , false, true , false, true , false, true },
   { -2, +1, -2, -1, false, true , false, true , false, true , false, true },
   { -1, +1, -2, -1, false, true , false, true , false, true , false, true },
   { +0, +1, -2, -1, false, true , false, true , false, true , false, true },
   { +1, +1, -2, -1, false, false, true , true , false, false, true , true },
   { -3, -3, -1, -1, false, true , false, true , true , false, true , false},
   { -2, -3, -1, -1, false, true , false, true , true , false, true , false},
   { -1, -3, -1, -1, false, true , false, true , true , false, true , false},
   { +0, -3, -1, -1, false, false, true , true , false, false, true , true },
   { +1, -3, -1, -1, true , false, true , false, false, true , false, true },
   { -3, -2, -1, -1, false, true , false, true , true , false, true , false},
   { -2, -2, -1, -1, false, true , false, true , true , false, true , false},
   { -1, -2, -1, -1, false, true , false, true , true , false, true , false},
   { +0, -2, -1, -1, false, false, true , true , false, false, true , true },
   { +1, -2, -1, -1, true , false, true , false, false, true , false, true },
   { -3, -1, -1, -1, false, true , false, true , true , false, true , false},
   { -2, -1, -1, -1, false, true , false, true , true , false, true , false},
   { -1, -1, -1, -1, false, true , false, true , true , false, true , false},
   { +0, -1, -1, -1, false, false, true , true , false, false, true , true },
   { +1, -1, -1, -1, true , false, true , false, false, true , false, true },
   { -3, +0, -1, -1, false, false, true , true , false, true , false, true },
   { -2, +0, -1, -1, false, false, true , true , false, true , false, true },
   { -1, +0, -1, -1, false, false, true , true , false, true , false, true },
   { +0, +0, -1, -1, false, false, true , true , false, false, false, false},
   { +1, +0, -1, -1, false, false, true , true , true , false, true , false},
   { -3, +1, -1, -1, false, true , false, true , false, true , false, true },
   { -2, +1, -1, -1, false, true , false, true , false, true , false, true },
   { -1, +1, -1, -1, false, true , false, true , false, true , false, true },
   { +0, +1, -1, -1, false, false, true , true , false, false, true , true },
   { +1, +1, -1, -1, true , false, true , false, true , false, true , false},
   { -3, -3, +0, -1, false, true , false, true , true , false, true , false},
   { -2, -3, +0, -1, false, true , false, true , true , false, true , false},
   { -1, -3, +0, -1, false, true , false, true , true , false, true , false},
   { +0, -3, +0, -1, true , false, true , false, true , false, true , false},
   { +1, -3, +0, -1, true , false, true , false, true , false, true , false},
   { -3, -2, +0, -1, false, true , false, true , true , false, true , false},
   { -2, -2, +0, -1, false, true , false, true , true , false, true , false},
   { -1, -2, +0, -1, false, true , false, true , true , false, true , false},
   { +0, -2, +0, -1, true , false, true , false, true , false, true , false},
   { +1, -2, +0, -1, true , false, true , false, true , false, true , false},
   { -3, -1, +0, -1, false, true , false, true , true , false, true , false},
   { -2, -1, +0, -1, false, true , false, true , true , false, true , false},
   { -1, -1, +0, -1, false, false, true , true , true , false, true , false},
   { +0, -1, +0, -1, true , false, true , false, true , false, true , false},
   { +1, -1, +0, -1, true , false, true , false, false, false, true , true },
   { -3, +0, +0, -1, true , false, true , false, false, true , false, true },
   { -2, +0, +0, -1, true , false, true , false, false, true , false, true },
   { -1, +0, +0, -1, true , false, true , false, false, true , false, true },
   { +0, +0, +0, -1, true , false, true , false, false, false, false, false},
   { +1, +0, +0, -1, true , false, true , false, true , false, true , false},
   { -3, +1, +0, -1, false, true , false, true , false, true , false, true },
   { -2, +1, +0, -1, false, true , false, true , false, true , false, true },
   { -1, +1, +0, -1, false, false, true , true , false, false, true , true },
   { +0, +1, +0, -1, true , false, true , false, true , false, true , false},
   { +1, +1, +0, -1, true , false, true , false, true , false, true , false},
   { -3, -3, +1, -1, false, true , false, true , true , false, true , false},
   { -2, -3, +1, -1, false, true , false, true , true , false, true , false},
   { -1, -3, +1, -1, true , false, true , false, true , false, true , false},
   { +0, -3, +1, -1, true , false, true , false, true , false, true , false},
   { +1, -3, +1, -1, true , false, true , false, true , false, true , false},
   { -3, -2, +1, -1, false, true , false, true , true , false, true , false},
   { -2, -2, +1, -1, false, true , false, true , true , false, true , false},
   { -1, -2, +1, -1, true , false, true , false, true , false, true , false},
   { +0, -2, +1, -1, true , false, true , false, true , false, true , false},
   { +1, -2, +1, -1, true , false, true , false, true , false, true , false},
   { -3, -1, +1, -1, false, true , false, true , true , false, true , false},
   { -2, -1, +1, -1, false, false, true , true , true , false, true , false},
   { -1, -1, +1, -1, true , false, true , false, true , false, true , false},
   { +0, -1, +1, -1, true , false, true , false, true , false, true , false},
   { +1, -1, +1, -1, true , false, true , false, true , false, true , false},
   { -3, +0, +1, -1, true , false, true , false, false, true , false, true },
   { -2, +0, +1, -1, true , false, true , false, false, true , false, true },
   { -1, +0, +1, -1, true , false, true , false, false, true , false, true },
   { +0, +0, +1, -1, true , false, true , false, false, false, false, false},
   { +1, +0, +1, -1, true , false, true , false, true , false, true , false},
   { -3, +1, +1, -1, false, true , false, true , false, true , false, true },
   { -2, +1, +1, -1, false, false, true , true , false, false, true , true },
   { -1, +1, +1, -1, true , false, true , false, true , false, true , false},
   { +0, +1, +1, -1, true , false, true , false, true , false, true , false},
   { +1, +1, +1, -1, true , false, true , false, true , false, true , false},
   { -3, -3, -3, +0, false, true , false, true , false, true , false, true },
   { -2, -3, -3, +0, false, true , false, true , false, true , false, true },
   { -1, -3, -3, +0, false, true , false, true , false, true , false, true },
   { +0, -3, -3, +0, false, true , false, true , false, true , false, true },
   { +1, -3, -3, +0, false, true , false, true , false, true , false, true },
   { -3, -2, -3, +0, false, true , false, true , false, true , false, true },
   { -2, -2, -3, +0, false, true , false, true , false, true , false, true },
   { -1, -2, -3, +0, false, true , false, true , false, true , false, true },
   { +0, -2, -3, +0, false, true , false, true , false, true , false, true },
   { +1, -2, -3, +0, false, true , false, true , false, true , false, true },
   { -3, -1, -3, +0, false, true , false, true , false, false, true , true },
   { -2, -1, -3, +0, false, true , false, true , false, true , false, true },
   { -1, -1, -3, +0, false, true , false, true , false, true , false, true },
   { +0, -1, -3, +0, false, true , false, true , false, true , false, true },
   { +1, -1, -3, +0, false, true , false, true , false, true , false, true },
   { -3, +0, -3, +0, false, true , false, true , false, true , false, true },
   { -2, +0, -3, +0, false, true , false, true , false, true , false, true },
   { -1, +0, -3, +0, false, true , false, true , false, true , false, true },
   { +0, +0, -3, +0, false, true , false, true , false, false, false, false},
   { +1, +0, -3, +0, false, true , false, true , true , false, true , false},
   { -3, +1, -3, +0, false, true , false, true , false, true , false, true },
   { -2, +1, -3, +0, false, true , false, true , false, true , false, true },
   { -1, +1, -3, +0, false, true , false, true , false, true , false, true },
   { +0, +1, -3, +0, false, true , false, true , false, true , false, true },
   { +1, +1, -3, +0, false, true , false, true , false, true , false, true },
   { -3, -3, -2, +0, false, true , false, true , false, true , false, true },
   { -2, -3, -2, +0, false, true , false, true , false, true , false, true },
   { -1, -3, -2, +0, false, true , false, true , false, true , false, true },
   { +0, -3, -2, +0, false, true , false, true , false, true , false, true },
   { +1, -3, -2, +0, false, true , false, true , false, true , false, true },
   { -3, -2, -2, +0, false, true , false, true , false, true , false, true },
   { -2, -2, -2, +0, false, true , false, true , false, true , false, true },
   { -1, -2, -2, +0, false, true , false, true , false, true , false, true },
   { +0, -2, -2, +0, false, true , false, true , false, true , false, true },
   { +1, -2, -2, +0, false, true , false, true , false, true , false, true },
   { -3, -1, -2, +0, false, true , false, true , true , false, true , false},
   { -2, -1, -2, +0, false, true , false, true , false, false, true , true },
   { -1, -1, -2, +0, false, true , false, true , false, true , false, true },
   { +0, -1, -2, +0, false, true , false, true , false, true , false, true },
   { +1, -1, -2, +0, false, true , false, true , false, true , false, true },
   { -3, +0, -2, +0, false, true , false, true , false, true , false, true },
   { -2, +0, -2, +0, false, true , false, true , false, true , false, true },
   { -1, +0, -2, +0, false, true , false, true , false, true , false, true },
   { +0, +0, -2, +0, false, true , false, true , false, false, false, false},
   { +1, +0, -2, +0, false, true , false, true , true , false, true , false},
   { -3, +1, -2, +0, false, true , false, true , false, true , false, true },
   { -2, +1, -2, +0, false, true , false, true , false, true , false, true },
   { -1, +1, -2, +0, false, true , false, true , false, true , false, true },
   { +0, +1, -2, +0, false, true , false, true , false, true , false, true },
   { +1, +1, -2, +0, false, true , false, true , false, true , false, true },
   { -3, -3, -1, +0, false, true , false, true , false, false, true , true },
   { -2, -3, -1, +0, false, true , false, true , false, true , false, true },
   { -1, -3, -1, +0, false, true , false, true , false, true , false, true },
   { +0, -3, -1, +0, false, true , false, true , false, true , false, true },
   { +1, -3, -1, +0, true , false, true , false, false, true , false, true },
   { -3, -2, -1, +0, false, true , false, true , true , false, true , false},
   { -2, -2, -1, +0, false, true , false, true , false, false, true , true },
   { -1, -2, -1, +0, false, true , false, true , false, true , false, true },
   { +0, -2, -1, +0, false, true , false, true , false, true , false, true },
   { +1, -2, -1, +0, true , false, true , false, false, true , false, true },
   { -3, -1, -1, +0, false, true , false, true , true , false, true , false},
   { -2, -1, -1, +0, false, true , false, true , true , false, true , false},
   { -1, -1, -1, +0, false, true , false, true , false, false, true , true },
   { +0, -1, -1, +0, false, true , false, true , false, true , false, true },
   { +1, -1, -1, +0, false, false, true , true , false, true , false, true },
   { -3, +0, -1, +0, false, true , false, true , false, true , false, true },
   { -2, +0, -1, +0, false, true , false, true , false, true , false, true },
   { -1, +0, -1, +0, false, true , false, true , false, true , false, true },
   { +0, +0, -1, +0, false, true , false, true , false, false, false, false},
   { +1, +0, -1, +0, false, true , false, true , true , false, true , false},
   { -3, +1, -1, +0, false, true , false, true , false, true , false, true },
   { -2, +1, -1, +0, false, true , false, true , false, true , false, true },
   { -1, +1, -1, +0, false, true , false, true , false, true , false, true },
   { +0, +1, -1, +0, false, true , false, true , false, true , false, true },
   { +1, +1, -1, +0, false, false, true , true , false, false, true , true },
   { -3, -3, +0, +0, false, true , false, true , true , false, true , false},
   { -2, -3, +0, +0, false, true , false, true , true , false, true , false},
   { -1, -3, +0, +0, false, true , false, true , true , false, true , false},
   { +0, -3, +0, +0, false, false, true , true , false, false, true , true },
   { +1, -3, +0, +0, true , false, true , false, false, true , false, true },
   { -3, -2, +0, +0, false, true , false, true , true , false, true , false},
   { -2, -2, +0, +0, false, true , false, true , true , false, true , false},
   { -1, -2, +0, +0, false, true , false, true , true , false, true , false},
   { +0, -2, +0, +0, false, false, true , true , false, false, true , true },
   { +1, -2, +0, +0, true , false, true , false, false, true , false, true },
   { -3, -1, +0, +0, false, true , false, true , true , false, true , false},
   { -2, -1, +0, +0, false, true , false, true , true , false, true , false},
   { -1, -1, +0, +0, false, true , false, true , true , false, true , false},
   { +0, -1, +0, +0, false, false, true , true , false, false, true , true },
   { +1, -1, +0, +0, true , false, true , false, false, true , false, true },
   { -3, +0, +0, +0, false, false, true , true , false, true , false, true },
   { -2, +0, +0, +0, false, false, true , true , false, true , false, true },
   { -1, +0, +0, +0, false, false, true , true , false, true , false, true },
   { +0, +0, +0, +0, false, false, true , true , false, false, false, false},
   { +1, +0, +0, +0, false, false, true , true , true , false, true , false},
   { -3, +1, +0, +0, false, true , false, true , false, true , false, true },
   { -2, +1, +0, +0, false, true , false, true , false, true , false, true },
   { -1, +1, +0, +0, false, true , false, true , false, true , false, true },
   { +0, +1, +0, +0, false, false, true , true , false, false, true , true },
   { +1, +1, +0, +0, true , false, true , false, true , false, true , false},
   { -3, -3, +1, +0, false, true , false, true , true , false, true , false},
   { -2, -3, +1, +0, false, true , false, true , true , false, true , false},
   { -1, -3, +1, +0, false, true , false, true , true , false, true , false},
   { +0, -3, +1, +0, true , false, true , false, true , false, true , false},
   { +1, -3, +1, +0, true , false, true , false, true , false, true , false},
   { -3, -2, +1, +0, false, true , false, true , true , false, true , false},
   { -2, -2, +1, +0, false, true , false, true , true , false, true , false},
   { -1, -2, +1, +0, false, true , false, true , true , false, true , false},
   { +0, -2, +1, +0, true , false, true , false, true , false, true , false},
   { +1, -2, +1, +0, true , false, true , false, true , false, true , false},
   { -3, -1, +1, +0, false, true , false, true , true , false, true , false},
   { -2, -1, +1, +0, false, true , false, true , true , false, true , false},
   { -1, -1, +1, +0, false, false, true , true , true , false, true , false},
   { +0, -1, +1, +0, true , false, true , false, true , false, true , false},
   { +1, -1, +1, +0, true , false, true , false, false, false, true , true },
   { -3, +0, +1, +0, true , false, true , false, false, true , false, true },
   { -2, +0, +1, +0, true , false, true , false, false, true , false, true },
   { -1, +0, +1, +0, true , false, true , false, false, true , false, true },
   { +0, +0, +1, +0, true , false, true , false, false, false, false, false},
   { +1, +0, +1, +0, true , false, true , false, true , false, true , false},
   { -3, +1, +1, +0, false, true , false, true , false, true , false, true },
   { -2, +1, +1, +0, false, true , false, true , false, true , false, true },
   { -1, +1, +1, +0, false, false, true , true , false, false, true , true },
   { +0, +1, +1, +0, true , false, true , false, true , false, true , false},
   { +1, +1, +1, +0, true , false, true , false, true , false, true , false},
   { -3, -3, -3, +1, false, true , false, true , false, true , false, true },
   { -2, -3, -3, +1, false, true , false, true , false, true , false, true },
   { -1, -3, -3, +1, false, true , false, true , false, true , false, true },
   { +0, -3, -3, +1, false, true , false, true , false, true , false, true },
   { +1, -3, -3, +1, false, true , false, true , false, true , false, true },
   { -3, -2, -3, +1, false, true , false, true , false, true , false, true },
   { -2, -2, -3, +1, false, true , false, true , false, true , false, true },
   { -1, -2, -3, +1, false, true , false, true , false, true , false, true },
   { +0, -2, -3, +1, false, true , false, true , false, true , false, true },
   { +1, -2, -3, +1, false, true , false, true , false, true , false, true },
   { -3, -1, -3, +1, false, true , false, true , false, true , false, true },
   { -2, -1, -3, +1, false, true , false, true , false, true , false, true },
   { -1, -1, -3, +1, false, true , false, true , false, true , false, true },
   { +0, -1, -3, +1, false, true , false, true , false, true , false, true },
   { +1, -1, -3, +1, false, true , false, true , false, true , false, true },
   { -3, +0, -3, +1, false, true , false, true , false, true , false, true },
   { -2, +0, -3, +1, false, true , false, true , false, true , false, true },
   { -1, +0, -3, +1, false, true , false, true , false, true , false, true },
   { +0, +0, -3, +1, false, true , false, true , false, false, false, false},
   { +1, +0, -3, +1, false, true , false, true , true , false, true , false},
   { -3, +1, -3, +1, false, true , false, true , false, true , false, true },
   { -2, +1, -3, +1, false, true , false, true , false, true , false, true },
   { -1, +1, -3, +1, false, true , false, true , false, true , false, true },
   { +0, +1, -3, +1, false, true , false, true , false, true , false, true },
   { +1, +1, -3, +1, false, true , false, true , false, true , false, true },
   { -3, -3, -2, +1, false, true , false, true , false, true , false, true },
   { -2, -3, -2, +1, false, true , false, true , false, true , false, true },
   { -1, -3, -2, +1, false, true , false, true , false, true , false, true },
   { +0, -3, -2, +1, false, true , false, true , false, true , false, true },
   { +1, -3, -2, +1, false, true , false, true , false, true , false, true },
   { -3, -2, -2, +1, false, true , false, true , false, true , false, true },
   { -2, -2, -2, +1, false, true , false, true , false, true , false, true },
   { -1, -2, -2, +1, false, true , false, true , false, true , false, true },
   { +0, -2, -2, +1, false, true , false, true , false, true , false, true },
   { +1, -2, -2, +1, false, true , false, true , false, true , false, true },
   { -3, -1, -2, +1, false, true , false, true , false, false, true , true },
   { -2, -1, -2, +1, false, true , false, true , false, true , false, true },
   { -1, -1, -2, +1, false, true , false, true , false, true , false, true },
   { +0, -1, -2, +1, false, true , false, true , false, true , false, true },
   { +1, -1, -2, +1, false, true , false, true , false, true , false, true },
   { -3, +0, -2, +1, false, true , false, true , false, true , false, true },
   { -2, +0, -2, +1, false, true , false, true , false, true , false, true },
   { -1, +0, -2, +1, false, true , false, true , false, true , false, true },
   { +0, +0, -2, +1, false, true , false, true , false, false, false, false},
   { +1, +0, -2, +1, false, true , false, true , true , false, true , false},
   { -3, +1, -2, +1, false, true , false, true , false, true , false, true },
   { -2, +1, -2, +1, false, true , false, true , false, true , false, true },
   { -1, +1, -2, +1, false, true , false, true , false, true , false, true },
   { +0, +1, -2, +1, false, true , false, true , false, true , false, true },
   { +1, +1, -2, +1, false, true , false, true , false, true , false, true },
   { -3, -3, -1, +1, false, true , false, true , false, true , false, true },
   { -2, -3, -1, +1, false, true , false, true , false, true , false, true },
   { -1, -3, -1, +1, false, true , false, true , false, true , false, true },
   { +0, -3, -1, +1, false, true , false, true , false, true , false, true },
   { +1, -3, -1, +1, false, true , false, true , false, true , false, true },
   { -3, -2, -1, +1, false, true , false, true , false, true , false, true },
   { -2, -2, -1, +1, false, true , false, true , false, true , false, true },
   { -1, -2, -1, +1, false, true , false, true , false, true , false, true },
   { +0, -2, -1, +1, false, true , false, true , false, true , false, true },
   { +1, -2, -1, +1, false, true , false, true , false, true , false, true },
   { -3, -1, -1, +1, false, true , false, true , true , false, true , false},
   { -2, -1, -1, +1, false, true , false, true , false, false, true , true },
   { -1, -1, -1, +1, false, true , false, true , false, true , false, true },
   { +0, -1, -1, +1, false, true , false, true , false, true , false, true },
   { +1, -1, -1, +1, false, true , false, true , false, true , false, true },
   { -3, +0, -1, +1, false, true , false, true , false, true , false, true },
   { -2, +0, -1, +1, false, true , false, true , false, true , false, true },
   { -1, +0, -1, +1, false, true , false, true , false, true , false, true },
   { +0, +0, -1, +1, false, true , false, true , false, false, false, false},
   { +1, +0, -1, +1, false, true , false, true , true , false, true , false},
   { -3, +1, -1, +1, false, true , false, true , false, true , false, true },
   { -2, +1, -1, +1, false, true , false, true , false, true , false, true },
   { -1, +1, -1, +1, false, true , false, true , false, true , false, true },
   { +0, +1, -1, +1, false, true , false, true , false, true , false, true },
   { +1, +1, -1, +1, false, true , false, true , false, true , false, true },
   { -3, -3, +0, +1, false, true , false, true , false, false, true , true },
   { -2, -3, +0, +1, false, true , false, true , false, true , false, true },
   { -1, -3, +0, +1, false, true , false, true , false, true , false, true },
   { +0, -3, +0, +1, false, true , false, true , false, true , false, true },
   { +1, -3, +0, +1, true , false, true , false, false, true , false, true },
   { -3, -2, +0, +1, false, true , false, true , true , false, true , false},
   { -2, -2, +0, +1, false, true , false, true , false, false, true , true },
   { -1, -2, +0, +1, false, true , false, true , false, true , false, true },
   { +0, -2, +0, +1, false, true , false, true , false, true , false, true },
   { +1, -2, +0, +1, true , false, true , false, false, true , false, true },
   { -3, -1, +0, +1, false, true , false, true , true , false, true , false},
   { -2, -1, +0, +1, false, true , false, true , true , false, true , false},
   { -1, -1, +0, +1, false, true , false, true , false, false, true , true },
   { +0, -1, +0, +1, false, true , false, true , false, true , false, true },
   { +1, -1, +0, +1, false, false, true , true , false, true , false, true },
   { -3, +0, +0, +1, false, true , false, true , false, true , false, true },
   { -2, +0, +0, +1, false, true , false, true , false, true , false, true },
   { -1, +0, +0, +1, false, true , false, true , false, true , false, true },
   { +0, +0, +0, +1, false, true , false, true , false, false, false, false},
   { +1, +0, +0, +1, false, true , false, true , true , false, true , false},
   { -3, +1, +0, +1, false, true , false, true , false, true , false, true },
   { -2, +1, +0, +1, false, true , false, true , false, true , false, true },
   { -1, +1, +0, +1, false, true , false, true , false, true , false, true },
   { +0, +1, +0, +1, false, true , false, true , false, true , false, true },
   { +1, +1, +0, +1, false, false, true , true , false, false, true , true },
   { -3, -3, +1, +1, false, true , false, true , true , false, true , false},
   { -2, -3, +1, +1, false, true , false, true , true , false, true , false},
   { -1, -3, +1, +1, false, true , false, true , true , false, true , false},
   { +0, -3, +1, +1, false, false, true , true , false, false, true , true },
   { +1, -3, +1, +1, true , false, true , false, false, true , false, true },
   { -3, -2, +1, +1, false, true , false, true , true , false, true , false},
   { -2, -2, +1, +1, false, true , false, true , true , false, true , false},
   { -1, -2, +1, +1, false, true , false, true , true , false, true , false},
   { +0, -2, +1, +1, false, false, true , true , false, false, true , true },
   { +1, -2, +1, +1, true , false, true , false, false, true , false, true },
   { -3, -1, +1, +1, false, true , false, true , true , false, true , false},
   { -2, -1, +1, +1, false, true , false, true , true , false, true , false},
   { -1, -1, +1, +1, false, true , false, true , true , false, true , false},
   { +0, -1, +1, +1, false, false, true , true , false, false, true , true },
   { +1, -1, +1, +1, true , false, true , false, false, true , false, true },
   { -3, +0, +1, +1, false, false, true , true , false, true , false, true },
   { -2, +0, +1, +1, false, false, true , true , false, true , false, true },
   { -1, +0, +1, +1, false, false, true , true , false, true , false, true },
   { +0, +0, +1, +1, false, false, true , true , false, false, false, false},
   { +1, +0, +1, +1, false, false, true , true , true , false, true , false},
   { -3, +1, +1, +1, false, true , false, true , false, true , false, true },
   { -2, +1, +1, +1, false, true , false, true , false, true , false, true },
   { -1, +1, +1, +1, false, true , false, true , false, true , false, true },
   { +0, +1, +1, +1, false, false, true , true , false, false, true , true },
   { +1, +1, +1, +1, true , false, true , false, true , false, true , false},
  };

int main(int argc, char **argv) {
  for(int i=0;i<sizeof(cases)/sizeof(Case);i++) {
    double a = cases[i].a;
    double b = cases[i].b;
    double c = cases[i].c;
    double d = cases[i].d;

    if (b >= 0 && func0(a, b, c, d) != cases[i].b0) {
      printf("func0 : %g, %g, %g, %g\n", a, b, c, d);
      exit(1);
    }
    if (b >= 0 && func1(a, b, c, d) != cases[i].b1) {
      printf("func1 : %g, %g, %g, %g\n", a, b, c, d);
      exit(1);
    }
    if (b >= 0 && func2(a, b, c, d) != cases[i].b2) {
      printf("func2 : %g, %g, %g, %g\n", a, b, c, d);
      exit(1);
    }
    if (b >= 0 && func3(a, b, c, d) != cases[i].b3) {
      printf("func3 : %g, %g, %g, %g\n", a, b, c, d);
      exit(1);
    }
    if (b != 0 && func4(a, b, c, d) != cases[i].b4) {
      printf("func4 : %g, %g, %g, %g\n", a, b, c, d);
      exit(1);
    }
    if (b != 0 && func5(a, b, c, d) != cases[i].b5) {
      printf("func5 : %g, %g, %g, %g\n", a, b, c, d);
      exit(1);
    }
    if (b != 0 && func6(a, b, c, d) != cases[i].b6) {
      printf("func6 : %g, %g, %g, %g\n", a, b, c, d);
      exit(1);
    }
    if (b != 0 && func7(a, b, c, d) != cases[i].b7) {
      printf("func7 : %g, %g, %g, %g\n", a, b, c, d);
      exit(1);
    }
  }

  printf("Pass\n");

  exit(0);
}

#else
void genCase(double w, double x, double y, double z) {
  printf("{ %+g, %+g, %+g, %+g, ", w, x, y, z);
  printf("%s, ", func0(w, x, y, z) ? "true " : "false");
  printf("%s, ", func1(w, x, y, z) ? "true " : "false");
  printf("%s, ", func2(w, x, y, z) ? "true " : "false");
  printf("%s, ", func3(w, x, y, z) ? "true " : "false");
  printf("%s, ", func4(w, x, y, z) ? "true " : "false");
  printf("%s, ", func5(w, x, y, z) ? "true " : "false");
  printf("%s, ", func6(w, x, y, z) ? "true " : "false");
  printf("%s},", func7(w, x, y, z) ? "true " : "false");
}

int main(int argc, char **argv) {
  for(int i = 0;i<5*5*5*5;i++) {
    double a[4];
    int k = i;
    for(int j=0;j<4;j++) {
      a[j] = (k % 5) - 3;
      k /= 5;
    }
    genCase(a[0], a[1], a[2], a[3]);
    printf("\n");
  }
}
#endif
